# Generated by Django 2.1.4 on 2019-05-18 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bloguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scheduled_post',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
