# Generated by Django 2.1.4 on 2019-05-18 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_scheduled_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='scheduled_post',
        ),
    ]
